### ISSUE TITLE
指令参数

### ISSUE THREAD

**Issue by leeluolee** [regularjs/regular#100]
提供指令参数功能，以`r-model`为例，比如我们要支持debounce 、delay配置

对于以下模板
```
<input r-model={formData.username} delay debounce=100 />
```
```js
Regular.directive("r-model", {
  params: ['delay', 'debounce'],
  link: function( elem, value, attrs, extra ){
     var params = extra.params; 
     console.log(params.delay) 输出delay
     console.log(params.deounce) 输出 100
  }
})
```
**进入指令参数列表的 属性不再会默认输出在节点上。**

**Comment by henryzp** [comment]
有问题额：

![image](https://cloud.githubusercontent.com/assets/3849702/18779787/0dc49036-81ad-11e6-99df-137cc4d94f03.png)

![image](https://cloud.githubusercontent.com/assets/3849702/18779793/145bf60a-81ad-11e6-9648-66a9939f89c7.png)

![image](https://cloud.githubusercontent.com/assets/3849702/18779799/19eb74d8-81ad-11e6-9aba-62302f16ca89.png)

有问题额。。。

版本：0.5.1

**Comment by henryzp** [comment]
经测试，上面的params改成param就好了。。

这。。。波神更新一下吧
