### ISSUE TITLE
关于computed计算属性

### ISSUE THREAD

**Issue by henryzp** [regularjs/regular#102]
我有这样一个需求：

一个表格，多个单元格，c依赖于a+b，就类似excel这样的功能。

```
var A = Regular.extend({
            template: '<input r-model="a" />, <input r-model="b" />,<input r-model="c" />{c}, <span on-click={this.show()}>点击</span>',
            show: function(){
                console.log(this.data);
            }
        })

        var comp = new A({
            data: {
                a: 1,
                b: 4,
                c: 0
            },
            computed: {
                c: {
                    get: function(data){
                        return data.a + data.b + 2;
                    }
                }
            }
        }).$inject("#dialogContent");
```

在show的时候，c的值还是为0，有没有办法得到正确的值？

**Comment by leeluolee** [comment]
要兼容低版本，所以不是通过Object.defineProperty实现的。  你要获得C的话，

`this.$get('c')`;   

this.$get  与  this.data  的区别就是   this.$get会build传进去的表达式，从而得到c这样的计算字段

 具体请参考 下面的文档 

http://regularjs.github.io/reference/?api-zh#api-reference-实例接口-componentget 

应该只有获得 计算字段 的 时候 才会 需要 调用 $get

**Comment by henryzp** [comment]
@leeluolee ，波大，请教一下，如果计算传入一个表达式，该怎么处理比较好？

比如说

```
"a + b +2"
```

在computed里面需要用this.a+this.b+2，然后还要eval一把。。有好的建议吗？而且这样的话，我一旦表格是数字，那表达式又要变成parseInt一堆东西，这样维护起来很累

**Comment by fengzilong** [comment]
@henryzp 看不太懂你上面的描述，不知道这个是否可以解决你issue中描述的问题？
https://jsfiddle.net/n2yz51c1/

**Comment by henryzp** [comment]
@fengzilong ，我的需求稍微复杂一些，就是一个字符串，a+b+2，其中a就是对应vm里面的a，b也是。。

现在就是想做到把字符串转为可以解析的，放到get的return中去。当然可以通过eval+with，改变作用域什么的。。

然而后面还有什么sum(a+b)，这样的语法解析器。。请问一下你有好的办法吗？

**Comment by fengzilong** [comment]
https://jsfiddle.net/n2yz51c1/1/
是这样子么？在computed属性中使用字符串作为表达式return
