### ISSUE TITLE
怎样$watch全部？

### ISSUE THREAD

**Issue by henryzp** [regularjs/regular#106]
我有这样的一个编辑需求，一开始我配了一个规则，可能是：

```
a > b + c
```

当这个条件成立时，dom节点disable。

但是后面b+c，还会改变，将这个规则写到html中是可以的，但是现在尽量要做到分离。

所以我的想法是监听所有input的变化，然后做出DOM的相关处理。

但是用

```
component.$watch("*", function(){})
```

会报错。

**Comment by leeluolee** [comment]
该写表达式的地方还是要写，  模板本来就是用来提取你的依赖并进行主动监听的，如果在模板之外做，就需要自行watch,  所谓的mustache那一套数据和模板尽量分离，在mvvm系统中是不成立的。  

如果你非要这么做

1. watch接受表达式，这个是regularjs parse做的充分的展现，你可以这样

```js

component.$watch('a+b', function(a和b的和， 旧的a和b的和){
})
```

2. 如果你要监听所有可能的变化，Regularjs其实内部暴露了一个叫`$update`的事件，但是由于可能被滥用，一直没有写到文档中，它会在一次脏值循环中假如有任何值发生改变就触发(前提这值是被监听了的)，**注意这个事件并不会告诉你是什么值发生了改变**

```js
this.$on('$update',function(){})
```

**Comment by henryzp** [comment]
@leeluolee ， thx
