### ISSUE TITLE
换行导致模板无法解析

### ISSUE THREAD

**Issue by simongfxu** [regularjs/regular#11]
> * 编辑器Web Storm 8
> * 操作系统 Mac OS X
> * 浏览器Chrome

## 模板内容

```html
<input type="text"  class="form-control"
						       id="username" name="username" value="">
```

## 错误内容

Uncaught Error: Parse Error: expect [>]" -> got "[UNQ]:
16> ..."form-control"

将模板内容移到一行之后就正常了，按下enter换行以后就会报错

**Comment by leeluolee** [comment]
\T导致的词法错误
