### ISSUE TITLE
增加指令directive定义的update函数

### ISSUE THREAD

**Issue by leeluolee** [regularjs/regular#110]
指令定义增加一个update函数

```
Regular.directive('xxx', {
    link: xxx,
    update: function(element, newvalue, oldvalue){
        
    }

})
```

这样当你使用 `<div   xxx={someProperty} > </div>`，会自动创建数据绑定，每当表达式someProperty发生改变，将会调用此方法，就无需再去link中创建watcher了。

_这么做主要是为了让开发者在大部分情况下都无需关心Expression这个抽象的存在_

**Comment by rainfore** [comment]
这个支不支持常量`<div xxx={true}></div>`？还有HTML5的风格`<div xxx ></div>`

我已经实现过一次了。。https://github.com/regular-ui/ui-base/blob/next/util/index.js
