### ISSUE TITLE
关于实时计算的问题

### ISSUE THREAD

**Issue by henryzp** [regularjs/regular#111]
比如说有两个表达式：

```
{
     "a": "b + c",
     "d": "e + f"
}
```

现在测试computed，当data数据改变时，所有的计算都会重新触发。

所以我在想，这个计算的时候，能不能处理到模型，当表达式里面的模型发生改变时，对应的计算才计算，而不是重新全部计算一次，在性能上感觉有所损耗。

**Comment by rainfore** [comment]
这个可以用
```javascript
this.$watch(['b', 'c'], (b, c) => this.data.a = b + c);
this.$watch(['e', 'f'], (e, f) => this.data.d = e + f);
```

**Comment by henryzp** [comment]
@rainfore  问题是我不知道b，c这个变量，我上面的是字符串，我不知道传入的是啥，可能会是很复杂的表达式。。

在这个表达式里面会用到很多模型字段。
