### ISSUE TITLE
有没有办法让r-model在失焦后做处理？

### ISSUE THREAD

**Issue by henryzp** [regularjs/regular#113]
针对input的情况。

就是在做计算的时候，能不能在鼠标失焦时，去做计算呢？

**Comment by leeluolee** [comment]
0.5.1   使用  lazy   `<input r-model =xx   lazy >`

**Comment by henryzp** [comment]
@leeluolee ，好的，这个和vue倒是一样的用法。。

**Comment by leeluolee** [comment]
@henryzp 因为有需求。

**Comment by henryzp** [comment]
@leeluolee ，嗯嗯，谢谢。。
