### ISSUE TITLE
关于regular的两个性能问题

### ISSUE THREAD

**Issue by henryzp** [regularjs/regular#114]
两个性能问题：

- #111 

- $watch的问题

在第一次改变相关的model时，会触发所有的$watch事件，之后就不会了。这个是一个bug吧？

测试地址: [$watch的问题](http://codepen.io/henryzp/pen/kXzmqJ/)

**Comment by leeluolee** [comment]
http://regularjs.github.io/guide/zh/advanced/dirty.html

**Comment by leeluolee** [comment]
http://mathieuancelin.github.io/js-repaint-perfs/regularjs/
对性能有顾虑的可以参考下这个case ,  你也可以在上级目录找到一些别的框架。 http://mathieuancelin.github.io/js-repaint-perfs/



这个case是早期的regularjs版本，目前最新的版本fps又提高了大概5-10.  处于绝对优势的阶层，比大部分virtual dom的框架都要快。

**Comment by leeluolee** [comment]
第一次触发的实际上是  undefined ->  当前值的  变化。
