### ISSUE TITLE
template中不能含有style这种吗？

### ISSUE THREAD

**Issue by henryzp** [regularjs/regular#117]
```
<script type="text/html" id="tpl">
    <style>
        .test{
            color: red;
        }
    </style>
    afdsafa
</script>
```

模板如上，内部在解析时，是碰到了样式的“{”，就会parse出错。

那我的想法是这样的：

基于模板耦合css，有时候不是太想挂一个link标签，纯粹是想用style标签，这样形成了一个闭环的Compontent。

将来在做移除css的时候，也方便移除。

说了这么多，就是想了解一下，将来的处理，能不能把style这一块也给考虑进去，当`{`在style标签里面不做解析，直接输出呢?

**Comment by conechan** [comment]
貌似有个 loader 实现了。https://github.com/regularjs/regular-loader

**Comment by fengzilong** [comment]
每个人书写css的方式可能不一样，比如会使用css预处理器，regular是跑在运行时的，而不是编译阶段，建议使用工具实现，比如上面提到的regular-loader

**Comment by leeluolee** [comment]
@fengzilong 暗搓搓  撸了个loader么。

**Comment by fengzilong** [comment]
@leeluolee 哈哈，被发现了

**Comment by henryzp** [comment]
@fengzilong ，有没有结合fis3的方案。。

因为我上面的style也不是说自己加上去的，而是通过

```
<link rel="stylesheet" type="text/css" href="a.css?__inline">
```

上面可以是css，也可以是less，或者其他预编译语言

所以可能对于不使用webpack的人，是一件很蛋疼的事。。

**Comment by fengzilong** [comment]
暂时没有fis3的解决方案，平时不用fis，所以就没有研究过，如果后面有了fis3的解决方案，我会在这个issue中回复的，当然也欢迎你自己研究一下，自己解决肯定是最快的，也能在这个过程中加深对fis和regular的理解
