### ISSUE TITLE
子组件属性与unsetable表达式数据绑定后报错

### ISSUE THREAD

**Issue by shhider** [regularjs/regular#122]
demo: [http://jsbin.com/jocumixivu/edit?html,js,console,output](http://jsbin.com/jocumixivu/edit?html,js,console,output)

demo中的组件组合中，子组件的``disabled``与外部组件的``myName|isJerry``表达式形成了双向绑定，但是后者表达式是一个单向过滤器，是unsetable的，regular无法处理产生报错。

需要的处理应该是

> 但是如果不是setable的， 应该是默认不做处理即降级为单向绑定，而不是抛错

**Comment by leeluolee** [comment]
经过检查这个问题是因为 引入双向过滤器导致 .
