### ISSUE TITLE
当计算过多时，报错

### ISSUE THREAD

**Issue by henryzp** [regularjs/regular#123]
因为涉及很多个input的计算，大概有上百个了，会报`there may a circular dependencies reaches`，请问会是什么原因？

```
$digest: function(){
     ...
     if((++n) > 20){ // max loop
	  throw Error('there may a circular dependencies reaches')
    }
    ...
}
```

猜测可能是有循环计算

**Comment by fengzilong** [comment]
可能是依赖中出现死循环，或者依赖过于复杂了，你可以把20调大试试，比如10000，如果还是有问题，那就是你代码逻辑有问题了
