### ISSUE TITLE
动态组件单选的问题

### ISSUE THREAD

**Issue by xiongxin** [regularjs/regular#132]
我有一个组件A，在里面动态注入了几个组件，每个子组件有个单选按钮，但是只能有一个是选中的状态，这些组件事可以动态增删的，这样子的功能该如何实现呢？

**Comment by fengzilong** [comment]
你说的动态注入是指`{#inc this.$body}`还是`component.$inject`？

**Comment by xiongxin** [comment]
我使用component.$inject注入的

**Comment by fengzilong** [comment]
那你应该有component的引用吧，在component内部$emit一个`checked`事件，在外部监听这个事件，然后处理就好了

**Comment by xiongxin** [comment]
@fengzilong 大神，这种动态添加dom结构的组件，怎么用面向数据的方式来写呢或者使用{#inc this.$body}怎么实现增删改查？能给个demo吗？

**Comment by fengzilong** [comment]
并不是大神，用`{#inc this.$body}`的话，可以看这个例子，用`list`或者`if`去控制你的子组件，其实就是regular常见的用法了
https://jsfiddle.net/6pLb4m3d/
RadioGroup和Radio的代码在这里
https://github.com/fengzilong/pure/tree/master/src/components/radio

**Comment by xiongxin** [comment]
@fengzilong 非常感谢！
