### ISSUE TITLE
0.5.x版本在node端运行报错

### ISSUE THREAD

**Issue by fengzilong** [regularjs/regular#133]
```bash
var devtools = window.__REGULAR_DEVTOOLS_GLOBAL_HOOK__;
               ^
ReferenceError: window is not defined
```

依赖了Regular.parse的webpack loader也会抛出下面的错误，导致无法正常工作

```bash
ERROR in window is not defined
```

**Comment by leeluolee** [comment]
0.5.1引入 devtools 代码时，未处理window的undefined 问题  。 这个问题本该被发现，是因为0.4的某个版本没有将node部分的case 引入到travis中

**Comment by leeluolee** [comment]
https://github.com/regularjs/regular/commit/13befa02fe0922872cdbe73b4a9f0efc5c13b06f

**Comment by fengzilong** [comment]
:thumbsup:
