### ISSUE TITLE
regularjs 0.5.2版本 nodejs环境下使用 Regular.parse() 会报错

### ISSUE THREAD

**Issue by zjzhome** [regularjs/regular#140]
报错信息: ERROR in window is not defined

排查是因为 版本中加入了devtools , window变量没有做判断

// check if regular devtools hook exists
var devtools = window.__REGULAR_DEVTOOLS_GLOBAL_HOOK__;
if (devtools) {
  Regular.prototype.devtools = devtools;
}

**Comment by gssan** [comment]
#133 已经提交过了
