### ISSUE TITLE
日期选择 DatePicker:年份部分二次修改，可以修改为s

### ISSUE THREAD

**Issue by leileiqiu** [regularjs/regular#141]
![image](https://cloud.githubusercontent.com/assets/17823144/20613683/4c99a500-b301-11e6-9f38-e4dbae19c641.png)

日期选择 DatePicker:年份部分第一次不能修改成功，第二次可以修改成s

**Comment by gssan** [comment]
这个应该是 [Regular-UI](https://github.com/regular-ui) 的问题，不是regular的问题
