### ISSUE TITLE
$watch方法，监听数组，当监听的值是obj，回调函数入参出错

### ISSUE THREAD

**Issue by rookiebob** [regularjs/regular#146]
`$watch([a,b],function(p1,p2){})`
当a是一个Data对象时，回调中的p1变成了一个普通的obj^_^
PS:regualr 版本 0.5.2

**Comment by capasky** [comment]
应该和 #154 的问题相关

**Comment by AndyRightNow** [comment]
神奇的是，`0.5.1` 却没有这个问题。

刚才在 `0.6.0-beta.1` 里重现了这个问题。

**Comment by leeluolee** [comment]
@AndyRightNow  0.6.0-beta.1 还未发布 #153 的 PR
