### ISSUE TITLE
能强制触发watch吗？不管值是否有变化

### ISSUE THREAD

**Issue by swit1983** [regularjs/regular#165]
问题是这样的，我用多个multipleSelect 模拟树操作，但是编辑的时候默认选中子节点有问题，因为父节点没有变化无法触发watch事件来修改子节点数据，而且多个watch 和渲染之间有个时间差。
具体可以看regularui 中的 SelectGroup。试了好多方法要疯了。

**Comment by nanokind** [comment]
最好可以给个复现的 demo，不是很理解你的问题，想要强制触发 watch，只要手动触发 watch 的 callback 就可以了，这个 issue 可能提到 regular-ui 的仓库比较合适，有问题的话再 reopen
