### ISSUE TITLE
template字符长度小于16时，会把template当做selector处理，执行dom.find方法

### ISSUE THREAD

**Issue by zjx1195688876** [regularjs/regular#168]
`if((typeof template === 'string' && template.length < 16) && (node = dom.find(template))) {
    template = node.innerHTML;
  }`

建议不要采用template.length < 16的方法判断，否则容易产生误判。可以单独写一个方法，判断template还是selector

**Comment by fengzilong** [comment]
duplicate #163 
主要还是为了向下兼容，而且不好判断到底是一个selector还是template
不考虑兼容的话，增加一个el属性也是可以的，template只接收模板，也不用判断了

**Comment by fengzilong** [comment]
先关了哦(´-ω-`)
