### ISSUE TITLE
r-class={{"f-white":true}} 会报错

### ISSUE THREAD

**Issue by lzf0402** [regularjs/regular#175]
r-class={{"f-white":true}} 会报错
0.4.3的版本

**Comment by whusl** [comment]
http://regularjs.github.io/reference/?api-zh#api-reference-指令-r-class

文档也老了，没更新了。。。

**Comment by whusl** [comment]
http://regularjs.github.io/reference/?api-zh#api-reference-指令-r-class

文档也老了，没更新了。。。
