### ISSUE TITLE
有没有路由支持呢？

### ISSUE THREAD

**Issue by magicwallboy** [regularjs/regular#180]
之前用过了regular，挺好用的，兼容性也不错，但是好像没有路由，官方有提供路由支持吗？

**Comment by fengzilong** [comment]
https://github.com/regularjs/regular-state

**Comment by magicwallboy** [comment]
谢谢，我想问下，我访问路由#/app，报这个错误是为什么呢？ 
Uncaught TypeError: Regular.isRegular is not a function

`
var Regular = require('regularjs');
var restate  = require('regular-state');

var IndexComponent = require('./components/index');



var App = new Regular({
    template : require('./app.html')
    
});

const routes = {
    'app' : {
        view : App
    },
    'app.index' : {
        view : IndexComponent
    }
};

restate().state(routes).start({
    view : document.getElementById('app')
});

`

**Comment by leeluolee** [comment]
内部用了 `Regular.isRegular`  ，这个API低版本Regular不存在，我临时fix下 https://github.com/regularjs/regular-state/issues/3 。  你也可以现在自己在代码里做个兼容。  

```
if(!Regular.isRegular){
Regular.isRegular = function( Comp ){
return Comp.prototype instanceof Regular;
}
}
```
