### ISSUE TITLE
用webpack打包的代码，如果regular是import进去，ie8以下模式会报错

### ISSUE THREAD

**Issue by lolipop99** [regularjs/regular#181]
version: 0.5.2

problem：用webpack打包的代码，如果regular是import进去，ie8以下模式会报错

example：import Regular from 'regularjs';

result：
![image](https://cloud.githubusercontent.com/assets/6138899/26137640/1638d8a0-3af6-11e7-823c-1dec302e157b.png)

**Comment by lolipop99** [comment]
还有个问题，渲染出来的模板在ie下有大量的空文本节点？

**Comment by leeluolee** [comment]
这个应该是warning 文本节点指的是注释么？

**Comment by lolipop99** [comment]
![image](https://cloud.githubusercontent.com/assets/6138899/26140455/7dc92f16-3b09-11e7-94d5-a8cf3eef19ae.png)
是这样子的，导致ie7下布局都乱了

**Comment by lolipop99** [comment]
html代码：
![image](https://cloud.githubusercontent.com/assets/6138899/26141063/897ed4e8-3b0c-11e7-8ca9-0b4c8604ac5b.png)
js代码插入：
![image](https://cloud.githubusercontent.com/assets/6138899/26141091/b3b01222-3b0c-11e7-89f5-3c456d431051.png)
![image](https://cloud.githubusercontent.com/assets/6138899/26141095/bbc81586-3b0c-11e7-9c5c-22c4712eb37b.png)

**Comment by lolipop99** [comment]
@leeluolee  大神，求问这是什么问题，是我引入template方式不对。只有ie7会有这问题出现空文本节点。业务场景都运行在ie7下。在线等。

**Comment by lolipop99** [comment]
@leeluolee 大神，求问这是什么问题，是我引入template方式不对吗。只有ie7会有这问题出现空文本节点。业务场景都运行在ie7下。在线等。

**Comment by leeluolee** [comment]
Regular会保留空白 作为空文本节点（根据你模板里是否留空）。   应该所有浏览器都有，  是不是在IE7下  影响布局了？

**Comment by lolipop99** [comment]
是的。现在布局被影响到了

**Comment by lolipop99** [comment]
是的。现在布局被影响到了。保留空白能理解。但是html写结构都会换行。现在换行被处理成空文本节点了

**Comment by leeluolee** [comment]
@lolipop99 换行+空格  和 单独空格， 在渲染时 是一样的。     这个问题暂时没法解决 。  可以使用正则先去掉标签内部的节点再传给template.  或者修改css布局， 取消inline-block这种布局方式。  后面版本可能考虑 自动去空格的快捷配置方式。

**Comment by lolipop99** [comment]
@leeluolee 我现在是用压缩去掉内部空白传给template。
没用es6多行字符串是为了html和js分开维护。

还有个问题：就是一个弹窗结构是操作后append to dom body，我想用Regular去绑定事件指令给弹窗。用什么方式好。

tips：请问有QQ群之类的问答组织吗

**Comment by lolipop99** [comment]
![image](https://cloud.githubusercontent.com/assets/6138899/26186733/2f11b524-3bc6-11e7-8fc0-d71d085f9af8.png)
ie7下，new了个dialog组件，$inject不成功。其他环境正常。

**Comment by lolipop99** [comment]
![image](https://cloud.githubusercontent.com/assets/6138899/26186872/6af5d34e-3bc7-11e7-8400-3c003f4f376a.png)

ie7下，new了个dialog组件，$inject不成功。其他环境正常。这边定位原因是低版本下，$inject不支持组合选择？

**Comment by lolipop99** [comment]
![image](https://cloud.githubusercontent.com/assets/6138899/26187064/de127070-3bc8-11e7-8ccd-872f86e86cb0.png)

ie7下，new了个dialog组件，$inject不成功。其他环境正常。这边定位原因是低版本下，$inject不支持组合选择？

**Comment by leeluolee** [comment]
不是  $inject 不要使用选择器，  如果IE9底下只支持  id选择器  。  内部并没有封装选择器

**Comment by leeluolee** [comment]
inject 建议 永远只传节点
