### ISSUE TITLE
body property support

### ISSUE THREAD

**Issue by leeluolee** [regularjs/regular#182]
36381b708dddfc004958e012efd22883b0563898

现在可以支持

```js
<A title={~ <div>{name}</div>} ></A>
```

的方式 传入 body类型的property了，Regular原本设计的多Context Tokenizer 终于派上了高级用途。你可以直接使用#include来使用这个属性

A.html

```html
{#include title}
```

 这种写法可以规避一些冗余的组合，例如

```js
<A>
 <A.Title><div>{name}</div></A.Title>
</A>
```
这里的A.Title 往往什么都未做，只是为了给outer component A传递自身的this.$body

```js

A.Title = Regular.extend({
   name: 'A.Title',
   init(){
      // 这里的$outer 指向A节点
      this.$outer.data.title = this.$body;
   }
})
```

有了 body property, 这种尴尬的组合就可以避免了。  

但是复杂的body类型参数，仍然建议以组合的方式传入

具体可以查看testcase 
https://github.com/regularjs/regular/blob/36381b708dddfc004958e012efd22883b0563898/test/spec/browser-bugfix.js#L478

**Comment by fengzilong** [comment]
等这个好久了 :grinning:

**Comment by fengzilong** [comment]
https://github.com/regularjs/regular/blob/903117a9978260ed5f5a00575398625ed5f96126/src/parser/Parser.js#L534

`{~ ...}`这个会不会和unary里的`~`冲突了

**Comment by leeluolee** [comment]
@fengzilong 呃，确实会  。   不过现在 只会匹配  {~    中间没有空格的。    不过确实之前如果  ~ 紧贴 {开始符号的  会被解释成 ~ unary

**Comment by fengzilong** [comment]
😢

**Comment by leeluolee** [comment]
@fengzilong  估计  不会有太大影响。   哎，考虑不仔细。  考虑给个文档说明

**Comment by fengzilong** [comment]
@leeluolee 嗯，老版本的unary`~`解析好像会报错，应该不会有人用这个，没什么关系~

**Comment by leeluolee** [comment]
done ! 忘记链接对应commit
