### ISSUE TITLE
[急]IE模式，Regular报源码错误。

### ISSUE THREAD

**Issue by lolipop99** [regularjs/regular#183]
如题，麻烦Regular相关工作人员排查一下。谢谢
![image](https://cloud.githubusercontent.com/assets/6138899/26352920/7ae2b27c-3ff0-11e7-86a1-541086f26c13.png)

![image](https://cloud.githubusercontent.com/assets/6138899/26352923/7e096f2c-3ff0-11e7-868f-afa58e016324.png)

定位源码位置：
![image](https://cloud.githubusercontent.com/assets/6138899/26352929/80e75286-3ff0-11e7-9470-4e448005eb27.png)

**Comment by lolipop99** [comment]
@leeluolee

**Comment by Mrlilili** [comment]
@leeluolee +1出现问题

**Comment by lolipop99** [comment]
@Mrlilili 波哥已经临时给了个解决方案
在引入Regular后 加入这段
`var dom = Regular.dom;
dom.text = (function (){
  var map = {};
  if (dom.msie && dom.msie < 9) {
    map[1] = 'innerText';    
    map[3] = 'nodeValue';    
  } else {
    map[1] = map[3] = 'textContent';
    try{
        var text = document.createTextNode('');
        text.textContent = 'void';
    }catch(e){
        map[1] = 'innerText';    
        map[3] = 'nodeValue';    
    }
  }
  
  return function (node, value) {
    var textProp = map[node.nodeType];
    if (value == null) {
      return textProp ? node[textProp] : '';
    }
    node[textProp] = value;
  }
})();`

RegularJS下个版本会解决这问题。
