### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by linjinying** [regularjs/regular#184]
regularjs的npm version定义不规范：`0.6.0-beta.3`，导致regular-loader安装失败。麻烦更新一下

**Comment by fengzilong** [comment]
报错能贴一下么？这应该不是regularjs的问题

**Comment by capasky** [comment]
`0.6.0-beta.3` 符合 semver规范的吧，参见 http://semver.org/lang/zh-CN/

**Comment by leeluolee** [comment]
@linjinying  尝试升级下 npm 版本

**Comment by linjinying** [comment]
@le
