### ISSUE TITLE
computed计算问题

### ISSUE THREAD

**Issue by leileiqiu** [regularjs/regular#191]
d2如果没有在模板中进行数据绑定，d2是不会计算的。怎样才能不在模板中绑定的情况下，让d2会计算。js中怎么去实现？
![image](https://user-images.githubusercontent.com/17823144/29363846-0d69c8b8-82c4-11e7-8339-864cf18e9b0d.png)

![image](https://user-images.githubusercontent.com/17823144/29363824-f679c784-82c3-11e7-9a85-c7065f64879f.png)

**Comment by fengzilong** [comment]
```js
this.$get( 'd2' )
```
