### ISSUE TITLE
enter 和 init

### ISSUE THREAD

**Issue by leileiqiu** [regularjs/regular#192]
enter 和 init 有什么区别？

**Comment by fengzilong** [comment]
enter是[regular-state](https://github.com/regularjs/regular-state)中引入的钩子，对应stateman的enter生命周期钩子，init是regular自身提供的钩子，在组件实例化时触发

以下描述都是假设你使用了regular-state

无论如何，每次路由进入都会触发enter
如果rebuild配置为false，那么init只会在第一次实例化组件时触发（发生在enter前）
如果rebuild配置为true，否则每次enter前都会重新实例化，触发init（发生在enter前）

可以直接看下代码
https://github.com/regularjs/regular-state/blob/master/restate-full.js#L161-L255
