### ISSUE TITLE
语法解析bug?

### ISSUE THREAD

**Issue by Neugls** [regularjs/regular#201]
![image](https://user-images.githubusercontent.com/1432749/34713991-e39ee9fc-f562-11e7-9696-8bd0e3b09157.png)
如上图所示， 如果含有&#34; 这样的转义内容会无法正常解析， 有什么解决 方案？

**Comment by leeluolee** [comment]
引号应该可以直接输入吧, 试着引用输入看看？   目前还没有处理&# 的方式载入html转义字符。 @Neugls

**Comment by Neugls** [comment]
@leeluolee  暂时使用了 r-html的方式解决了问题

**Comment by Neugls** [comment]
@leeluolee 我还发现， 如果含有#号都会出现问题， 比如说{#include dom},  如果dom 的值是 s#name, 那就会出现问题， 无法正常解析

**Comment by leeluolee** [comment]
@Neugls  针对这个问题，如果方便的可以建个独立的issue thx
