### ISSUE TITLE
r-model指令，建议通过CompositionEvent来实现

### ISSUE THREAD

**Issue by aweiu** [regularjs/regular#204]
郑大神好！

目前`r-model`监听的是input事件，在输入中文等需要字母待选的语言就会有很多不必要的触发，尤其是用于搜索的输入框。

如图：
![regular](https://user-images.githubusercontent.com/15623620/37817151-b8bb694a-2eb0-11e8-926f-4357304929da.gif)

建议改用[CompositionEvent](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent)来实现，效果如下：
![vue](https://user-images.githubusercontent.com/15623620/37817190-f212367e-2eb0-11e8-987d-40415fe800b9.gif)

**Comment by leeluolee** [comment]
fix了  下个版本发
