### ISSUE TITLE
safari浏览器，文本input绑定model，输入中文时出现取值异常bug

### ISSUE THREAD

**Issue by zengxingqi** [regularjs/regular#214]
如题，safari浏览器，当input输入中文时，会触发多次$watch事件，出现取值异常的bug。

regular有提供compositionend这样的事件吗？就我目前了解到的文档，好像并没有发现。

**Comment by leeluolee** [comment]
fix了 下个版本发， 参考 #204 描述。

即使现在的版本  你也可以 通过 `on-compositionend` 和 `on-compositionend`控制 。 Regular并不是每个新事件都需要重新支持， 而是默认支持所有事件。 具体看文档  http://regularjs.github.io/guide/zh/basic/event.html
