### ISSUE TITLE
双击事件中是否会触发单击事件

### ISSUE THREAD

**Issue by ldyjjm** [regularjs/regular#234]
在使用dblclick时，在双击时，在执行2次单击中的事件，这个要怎么解决？

**Comment by leeluolee** [comment]
你绑了on-click 就会触发 单击事件，这是浏览器默认行为。Regular事件系统完全就是代理原生的触发机制，没有任何奇技淫巧在里面。

**Comment by nanokind** [comment]
属于浏览器行为，如果是我们对你问题理解上的偏差，可以给个复现的 demo，方便我们更快定位问题，issue 我先关了
