### ISSUE TITLE
regular就是一个垃圾框架，文档写的就是坨屎

### ISSUE THREAD

**Issue by fsd789456** [regularjs/regular#238]
明明有更优秀的vue，react框架，还整天内部推行这个垃圾框架，和外界的主流开发隔离，就只为了自己的绩效。这个自嗨的regular生态能和外界社区相比？

**Comment by leeluolee** [comment]
@fsd789456 发泄可以，但要参考背景上下文，你这口气也看不出有任何素质。

- 首先Regular是与Vue同期产生的，可以看项目时间，最早的版本叫nm.js，那时候只是内部的一个库，13年底已经在易信线上使用了，Regular是组件化包装后的结果。

- 无论SSR还是路由框架都是Regular先于Vue实现，所以不存在 **明明已经有了这一说**

- 那时候React、Vue并没有现在那么火，而且我们需要兼容IE6、适配原有框架字符串模板语法等需求

你从时间点这个维度第一点应该去喷腾讯最近的框架才对。

我已经多次公开承认Regular现在并比不上市面上的主流框架，框架最后都是细节的比拼细节的技术运营，从文档、工具链都与业界有了一些比较大的差距。 **并且我们部门内部的主技术栈也是`React`**

> 还整天内部推行这个垃圾框架 

关于这一条，请问哪里看到我仍在推行？已经有大量项目已经在使用了，难道停止维护了，不更新技术链了？  周遭有部分部门已经在迁移，包含考拉，Regular有在阻止继续安利吗，也无权？

> 这个自嗨的regular生态能和外界社区相比？

如何自high?  你的论据是？


如果你是新人，让你站在5年前，你再去思考下，当时是否有必要。  我承认这个框架给我带来了很大的个人能力成长和早期的级别晋升上的优势。 **如果你在那个时候，有那个资源和能力沉淀，可能你也会做这个选择**

**Comment by leeluolee** [comment]
晒三天，不回复这种无意义的issue就关了。
