### ISSUE TITLE
报一个bug: dom.off 出错

### ISSUE THREAD

**Issue by Qquanwei** [regularjs/regular#240]
![image](https://user-images.githubusercontent.com/9263655/50901963-93251480-1454-11e9-96af-d27776098835.png)

**Comment by Qquanwei** [comment]
该问题仅在: 
regularjs 0.6.1 出现
0.6.0没有这个问题。

**Comment by leeluolee** [comment]
https://github.com/regularjs/regular/commit/0b556275238325ac154ab130d657d4b8254d2306 

fix了， 已紧急发布修复版本0.6.2   npm deprecate 了0.6.1。
