### ISSUE TITLE
这种三流框架别在内部推广了，现在一些新项目还继续用这落伍的框架，也不看看现在的主流是什么，搞的老子都不好从网易跳槽。

### ISSUE THREAD

**Issue by leetcode3654** [regularjs/regular#248]

**Comment by XGHeaven** [comment]
听说海波大佬已经不在内部推广这个框架了，如果你上面还在推广这个框架（可能会有一些目光略微短浅之人），我的建议是直接怼回去喽。

**Comment by leeluolee** [comment]
@leetcode3654  我看得到的所有较大的部门都在做技术栈升级了（包括我们），不知道你是哪个部门，我管理不了你们团队的选型，我也不想和你再重申啥历史背景了。

每次注册一个新号你也是够可以的，你觉得这样能恶心到谁呢？ 当务之急好好刷刷leetcode ，换个工作吧，你这积怨有点太深。

**走前叫我一声，我请你吃饭，不开玩笑。** 🥇

**Comment by fengzilong** [comment]
实在忍不住出来说几句，一个人的上限会因为他用什么框架被决定吗？因为用了 regular 找不到工作有点搞笑，用 regular 不妨碍你理解 mvvm，另外你可以选择成为 webpack、node、微服务、前端监控、离线化方案、构建发布方面的大佬，前端的领域没有这么狭隘，限制你的是 regular 吗？是你自己（破音）

另外业界“三流”框架多得很，有些是我看着从几百 star 到上万 star 的

https://github.com/sveltejs/svelte
https://github.com/cyclejs/cyclejs

他们算是几流的？不去鼓励这些作者，反而在这说风凉话，你很棒

如果真要说的话，最多也就是 vue ssr 这些 kpi 吧，很多人靠 vue ssr 还有 vue 社区各种现成的东西晋升，的确是会容易些，另外就是出去可以讲自己会 ElementUI，但是这些有什么难度吗？如果你把自己局限在这些上面，我估计你的天花板也快到了

（打完一大段话，我怕是要赶不上端午回家的车票了23333）

**Comment by XGHeaven** [comment]
@fengzilong 我觉得你说的很对，但是我还是要补充并略微反驳几句。

一个人的上限确实不会被他所用的框架所决定，但是却会被他所用的框架所限制。
这里的限制不仅仅有时间上的限制，也有思维上的限制，也包括很多方面的限制。

时间上，因为公司的业务，不得不去使用 regular，学习和 regular 相关的东西，也就是说你根本没有什么时间去仔细学习其他的框架。当然你也可以用 regular 只写完基础功能，不去管优化、架构、原理，留下一堆烂摊子，然后剩下的时间去自己学习。
思维上，同样是 regular，可能会限制你思考的方式，当你习惯 regular 之后，去写 react/vue 可能都是一股 regular 风格。
深度上，我一直坚信一句话，你不做某个领域一定成为不了某个领域的专家。就像是公司不用 react，你成不了 react 大佬，不用 angular 你也成不了 angular 大佬，你用 node 也成不了 node 大佬。在公司 regular 的这个大环境下，想成为大佬可能就很难了。

> 这里『大佬』指的只是技术能力比较强，不代表其他，换句话说也就是相当于高级开发。

另外，如果是自学成为的大佬，你觉得出去找工作会好找么？自学永远是缺少项目经验的，出去是社招又不是校招，比较吃项目经验，除非某些方面能力特别强。

不过话说回来，在我心中一直有一个疑问，如何在公司不使用某项技术的情况下成为某项技术的大佬？我思考了许久，一直没有找到答案。而且我也没有看到这样的例子。（比如网易不用 angular，我要成为 angular 大佬，网易很多部门不用 node，我要成为 node 大佬）

我不管你说的这些框架是几流的（有些我也没听说过），至少对外面的来讲，是有一定的吸引力的。
而且他们也是会追赶业界主流框架，但是 regular 好久没有看过有啥动静了，而且几乎都是内部人用，外面几乎没有用的。

不过我也想说下，跳槽其实是最简单的了，花几天刷下面试题，很轻松就可以了，然而如何提升自己却是最难的。。感觉自己从大三开始就找不到技术提升的方向了 😂 很迷茫。某项技术你知道早与晚其实并不影响你对他学习理解的深度。

**Comment by leeluolee** [comment]
@XGHeaven 

感觉你今天状态还算理性，表述上也挺稚嫩，听起来应该是个年轻人。

从老一辈角度，我先分享2个我的观点

- **不要轻易谈什么瓶颈期**：工作头5年内(特别是前3年)，我觉得没有啥资格说自己遇到了什么技术瓶颈期，可学的东西太多了，而且这个阶段基本奠定了你继续学习的节奏和基础。
- **向内看向前看**：外部环境是一个因素（主管不好，技术栈垃圾，同事傻逼等等），但主要因素还是靠自己。不要因为环境因素就忽视了自己的问题（这部分是自己可以掌握的）。

基于此，我多说一些，分享下我的经历

-----------------

12年我入职网易，当时的环境么，作如下替换就行了

1. Regular >  NEJ
2. Vue、React >  Backbone、jQuery、requirejs

我入职开始那会的工作差不多就是内部外包，比如为网易识字这个幼儿教育项目切图工作（兼容IE6）及为BI系统管理页面切图（申请写JS对方部门后台没允许）。  

入职时其实我算SP Offer，自诩精通Backbone，jQuery、requirejs，请体会下我入职后的环境感受。

### __后来呢？__


基于痛点，我头半年首先就写了一个基于NEJ的jQuery风格链式包装，叫NEJ.chainable，这个阶段也对外包装了个叫[nes](https://github.com/leeluolee/nes)的轮子，
性能指标么，自己看好了，当时为了客观直接用的sizzle的testcase。**很多人看到的「坑」，有些人看到的是机会，这个我在知乎应该也提过几次。**

我当时也沉下心学了NEJ，发现很多亮点，比如UMI系统设计是算得上超强的（注意是放那个时候，那时候的典型项目seajs其实也只是个800行代码的库），但其中也有很多缺点，比如无法传递隐式参数等，这个也一一给飞哥提了意见，这也导致了后面我结合UMI和[ui-router]()的思想, 写了一个独立的[stateman](https://github.com/leeluolee/stateman)，这也是[Regular-state]()的主要依赖。



> 好了，回到Regular

### 首先下个结论，Regular这个项目就目前来看，彻头彻尾的失败了，这句话放前两年说也没问题。

但是还是要补充下，Regular及其前身nm.js（那时候基于NEJ，非standalone）诞生于易信业务快速进展时期（13底-14年），至少也让网易甚至部分外部团队度过了需要兼容IE9-的时代。

当时其实设计虽然有些负担，但还算可以。代码呢，也还行。自卖自夸不行，找下现在是大拿的尤雨溪的评价吧（如果尤大不是客气话）

![image](https://user-images.githubusercontent.com/731333/59087968-d23e8f80-8938-11e9-9af1-9c95c039c6dd.png)

_上图的性能问题，其实0.5.0后就不错了, 可以参考[js-repaint-perfs](http://mathieuancelin.github.io/js-repaint-perfs/regularjs/)_

__我总结下在Regular失败，出的几个大问题是__

- **早期没有形成开源社区**，
  - **把扔上github当做了终点而不是开始**，网易当时整体缺乏 **开源基因**，**很遗憾我也没例外**
  - 当时扔出去后，早期其实有过一些有建设性意见的国外开发者，但对意见都不了了之了，沟通基本还是围绕公司线下或POPO
  - 一位考拉的小同学和我私聊时说了一句**「任何只是解决自身问题的技术都不会被理解」**，我觉得确实如此。
- **中期没有服务好内部**
  - **文档落后太久**，很多人甚至不知道有SSR的能力，而实际上Regular的SSR实现要比Vue更早，设计上本身就是对SSR友好的。
  - 在16年开始网易新员工涌入+ 外部技术体系结构已形成RVA三大阵营 + 以及我开始到业务部门之后，我开始犹豫裹足，导致Regular没有做好对内的服务
- **后期没有跟进业界的技术演进**，
  - 自身由于职责定位转变，也没有搭建出这个项目的后继贡献者，导致几乎算是崩盘了。

在说下我的收获，很多人认为我靠Regular在几年前获得了晋升机会，我觉得没有问题，Regular在影响力上升期间，确实是我晋升的一部分因素。

但我要补充的是，如果保持当时的节奏，即使不做Regular，我也会输出其他类似的东西，所以还是看个人的思考方式和做事方法。

Regular这个项目其实对我最大的收获其实是**「它算是让我很深入的去思考了视图层框架这个议题」**。带来的结果就是，现在很多情况下，都可以以「观察者视角」去看待在这个议题下的技术演进，能看到本质。



### 所以回到开头，我回复下你的观点和疑问


> 不过话说回来，在我心中一直有一个疑问，如何在公司不使用某项技术的情况下成为某项技术的大佬？我思考了许久，一直没有找到答案。而且我也没有看到这样的例子。（比如网易不用 angular，我要成为 angular 大佬，网易很多部门不用 node，我要成为 node 大佬）


React、Vue 都还到不了**领域**这个词，但我觉得没问题，**一项技术要去掌握他，最好的办法是在工作中去使用**。 Node就不可理喻了，为啥部门不用你就不能用？ 我也建议每个前端都应该掌握Node这个工具，毕竟受限浏览器端的话做不了太多的事情。掌握了Node是常规前端成为一个合格程序员的最短路径。

成为什么什么大佬真的太幼稚了。

> 时间上，因为公司的业务，不得不去使用 regular，学习和 regular 相关的东西，也就是说你根本没有什么时间去仔细学习其他的框架。当然你也可以用 regular 只写完基础功能，不去管优化、架构、原理，留下一堆烂摊子，然后剩下的时间去自己学习。

你如果天然认为Regular学习和其他框架是完全冲突的，那确实不会有任何收获，但事实是如何的？ 眼界确实要拔高。你也可以参考我早期的体会和做法。

> 思维上，同样是 regular，可能会限制你思考的方式，当你习惯 regular 之后，去写 react/vue 可能都是一股 regular 风格。

在我还深入在使用NEJ的期间（12-14年）也是我技术最专注的时刻，你不会发现我作品里有任何所谓浓浓的NEJ风格，只有我觉得正确的风格


### 最后

- 并不是所有问题都是环境的问题，更多的是自己的问题，**向内看向前看**
- 如果你继续沉得下心去凌晨申请github临时账号来issue肆意妄为，我承认确实拿你没办法，但你真的觉得有啥意思吗？ 我就点个close issue而已，真不值得。我为人如何，和我接触过的人比你有资格评判
- 首先可以提出问题，你也可以不给任何解决方案甚至没有建设性意见也成。但谩骂或在issue里弄些疑神疑鬼的东西，只能体现你个人素质的堪忧，这是怎么做人的问题

**Comment by leeluolee** [comment]
@XGHeaven 我似乎认错了人

**Comment by fengzilong** [comment]
并不是所有问题都是环境的问题 +1

[Have you ever felt discouraged?](https://github.com/staltz/ama/issues/35)

这个链接我想发很久了，把作者怼得没有信心维护下去我是第一次亲眼见到，在这里怼得很开心的话，建议去 jQuery 仓库发一条对 jQuery 的评价，学 jQuery 让自己找不到工作，让自己做不了 SSR，让我止步不前，让我陷入瓶颈，让我中午吃不饱饭。用一个词形容的话：自私

框架技术选型只有合不合适，看主不主流，在我印象中，只有为了生存的外包，才会从这个角度看问题（没有黑外包同学的意思）

如果想多点 vue 的开发经验，考拉这里有很多 vue 的外包项目，你愿意吗？我猜不愿意

假如你花时间去看懂 regular 源码、regular-state 源码、regular ssr 原理，我觉得在网易相关领域比你强的人不会太多

学习框架如何使用其实是最无聊的一项能力，真正能令自己成长的是学习框架的思想和实现。你非要说公司用了这个框架，我才能看懂它的源码，我是不信的。大多数人都是在工作之外的时间学习的，如果你像我一样在凌晨 4 点打开 GitHub，没有什么拦得住你的个人能力提升（斜眼

记得把自己目标定高一点，做一般人做不了的事，不要学个 vue、react 的用法就满足了

如果看到这里你还是想开小号，随便你，下次就不打这么多话啦，该说的都说了，直接 close 了

**Comment by XGHeaven** [comment]
@leeluolee @fengzilong 感谢大佬回复，最近忙项目没看到。不过我真的想澄清下，不是我匿名发的。只是当初 watch 了这个 repo，所以才进来看到了。

之前几个 issue 原本也不想回复的，但是看到大佬们强调个人能力，我就有点稍微坐不住了。个人能力固然重要，但是公司提供的平台也很重要。俗话说的话，「没有金刚钻，怎揽瓷器活」。但反过来思考，没有瓷器活，又要金刚钻何用？

换句话说就像是打魔兽一样，一个项目就是一场小型交战。如果没有战争，那么你的视野就在你家的附近，只关心于自身的开发，也不管这个开发是不是适合这场游戏以及接下来的交战，偶尔打打附近的野怪给英雄生个级，但是很难拓宽出去，外面仍然有大量的迷雾。但是如果有战争，那么每一次战斗，都会将你的视野向外拓展一点，也许有的多有的少，但是随着时间的推移，你就将获得整个地图的视野，而你的整个技能树也会更加成熟完整、更加适应战场的需要。

大佬们应该也有感悟，自己成长最快的时候就是在做项目的时候。也就是说在学习的初期，一个好的项目可以快速让你进去一个领域、一个社区，学习到最多的东西。而再往后面的学习，往往项目的作用就不大了。这个时候就要靠大佬们说的个人的能力、学习的能力了。

对于我们这些校招生来说，现在处于快速学习时期，一个好的项目至关重要。
而对于两位大佬来说，你们已经度过快速成长期了，所以你们才会强调个人的学习能力，思维的转变，以及对技术的思考等等。

所以，开这个小号的人有这样的抱怨我是完全可以理解的。

再说作为一个公司，要追求最大的 ROI（投入产出比），同样，一个人也是。入门期间，没有人指导你，没有真正的项目让你练习，公司还各种压榨你的时间。结果自己自学好几年，还不如别人写几个月正式的项目学的多。这 ROI 是有多低啊，我身边看到过不少这样的例子。

而且不管你做的什么，基本都是围绕着你手上的项目来的。像是海波大佬如果没有做很多项目，也就不会遇到那么多痛点。也就不会去思考如果解决，也就不会有很多新的框架。而且我觉得海波大佬看 NEJ 的源码肯定是内心已经想写一个东西来替代他了，或者说有一个自己的构思，看看 NEJ 是不是和自己想的一样之类的，很难说我啥都不想做，也不是为了项目，就只是想看源码（欢迎海波大佬打脸）。
