### ISSUE TITLE
能发布一个maven的webjars包吗？

### ISSUE THREAD

**Issue by Dreampie** [regularjs/regular#25]

**Comment by leeluolee** [comment]
可以， 具体的作用是预处理模板？  因为这边几乎都是node的构建栈.  可以说下你的需求， 我可以找同事帮助实现

**Comment by Dreampie** [comment]
http://www.webjars.org/  就是打包成一个静态jar包

**Comment by leeluolee** [comment]
oh  看了下， 简单的. 我到时候建个repo吧

**Comment by Dreampie** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cregular  还不能搜到regular的webjars包

**Comment by leeluolee** [comment]
回去过年了...  刚发了request了  ， 看他们的反馈速度 https://github.com/webjars/webjars/issues/877

**Comment by Dreampie** [comment]
我自己设计了一个[restful的框架](https://github.com/Dreampie/resty)想结合regularjs+requirejs+coffeescript+lesscss做一个小项目，我看了一下regular-state应该是类似route的一个东西对吗？那么使用基本的regular核心+state部分就可以构建前端mvvm了？

**Comment by leeluolee** [comment]
差不多是这样，因为现在的mvvm或多或少都和单页系统扯上了关系， 你这么理解也没有错误。

其实每一个regularjs组件就相当于一个mvvm的小型系统.   state或router相当于提供了一个更高层级的路由体系. 有点类似Backbone.Router 与Backbone.View + Model的关系。要不要引入state的关键在于. 

> 你程序的某个显示状态需不需要通过url来定位， 如果不需要其实通过 模版的if else 获取就可以解决了.

regular-state做的只是， __当某个url满足条件时， 将你配置的对应组件按层级扔到dom中去而已__ 

另外看了下你的框架, 目录结构很清晰. 但我本身不懂java了， 这个框架和Spring这种是属于竞品关系么？ 轻量级的框架为何不使用nodejs来开发呢？

**Comment by Dreampie** [comment]
这个比spring轻量好几个量级，核心代码只有200k左右，代码量极少，使用的概念也更容易理解，现在大部分的中小公司还是依赖java作为服务端，nodejs我也不熟，这个也是前段时间公司需要一个restful的框架来支持数据平台，要求简洁，门槛低，然后就产生了这个，也看了很多框架，多数庞大，复杂，学习成本高，简单点不会对团队开发进度造成影响，本身项目也不大，简单点也方便维护

**Comment by Dreampie** [comment]
regular-state 里面 requirejs的例子的js来源是你本地bower安装的吗，有安装地址或cdn地址吗？或者把所以的js打包到release里也好下载？

**Comment by leeluolee** [comment]
1. 嗯， 通过bower安装的.
2. 我们一般用requirejs, 网易内部也有一套类似requirejs的模块加载器
3. 无法include, 如果要异步加载， 可以利用requirejs的加载， regularjs只是库，只处理mvvm的部分
4. 公用的部分可以直接写在入口的index.html中啊， 这个和angular等类似， 如果你需要头尾也包含在单页中系统中， 就将其定义在第一级的app的state中， 接下去 app.blog  app.chat 等都会塞进第一级app的ref=view的节点内

**Comment by leeluolee** [comment]
由于regular-state 目前说实话 虽然内部再用，但是文档完全没跟上，  可能使用上会有些麻烦

**Comment by leeluolee** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cregularjs   有了
