### ISSUE TITLE
如何将组件从当前document中移除，但是不销毁?

### ISSUE THREAD

**Issue by swit1983** [regularjs/regular#250]
RT,有对应的方法吗？或者说像后台那样打开多个可以关闭的tab如何实现？

**Comment by leeluolee** [comment]
`component.inject(false)`  @swit1983

**Comment by swit1983** [comment]
> `component.inject(false)` @swit1983

能再请教一下吗？我在看文档跨组件通信的例子的时候[这里](http://regularjs.github.io/guide/topic/communication.html),在 Broadcastor.js  里面调用next方法调用父组件的modifyBodyComponent  有什么作用，不调用也是可行的吧。我在动态注入里面看的那个例子没看明白，OtherProvider 这个组件的modifyBodyComponent  不用做任何事情就可以了捕获到button组件的事件吗？
还有就是为什么不直接使用
```
config( data ){
       // const emitter = data.emitter;
        this._broadcast = this.$emit.bind(this);
        this._subscribe =  this.$on.bind(this);
    }
```
而是从外面传一个 new Regular @leeluolee

**Comment by leeluolee** [comment]
要简单处理，就直接依赖一个全局的emitter  比如  `new Regular`
