### ISSUE TITLE
plan to create  bootstrap-regularjs for providing common component

### ISSUE THREAD

**Issue by leeluolee** [regularjs/regular#28]
A component should based particular html+css.  using bootstrap beacuse of its Popularity

1. version: bootstrap 3.x.  lastest version.  __only ·css+html· is depended__
2. support: all component list in [bootstrap/javascript](http://getbootstrap.com/javascript/) and component that commonly used(date-picker, progress, notify.. etc) 
3. customize: providing building script (gulp command) for customizing package.

**Comment by xiongxin** [comment]
:heart: :heart: nice work!

**Comment by xmory** [comment]
支持！

**Comment by leeluolee** [comment]
请关注 @rainfore 同学的 regular-ui,  完成度很高。
- Site: http://regular-ui.github.io/   
- Project:  https://github.com/regular-ui/regular-ui 


http://regular-ui.github.io/bootstrap/  暂时不会维护了
