### ISSUE TITLE
list循环怎么声明局部变量或者对变量处理？

### ISSUE THREAD

**Issue by Dreampie** [regularjs/regular#33]
```javascript
{#list items as item}
      {item.a}
      {item.b}
{/list}
```

怎么对 item.a 全部拼接起来 ，怎么对item.b 求和 ，不想在后台处理好在发出来，因为会遍历两次

**Comment by leeluolee** [comment]
在 代码里做，  比如config。  不要再模板处理数据

**Comment by Dreampie** [comment]
那不是config里面循环处理一次，模版解析的时候还会循环一次？

**Comment by leeluolee** [comment]
你可以在一次循环里 把a属性的的拼接， 和b的求和做了。  
模板是用来展现， 能声明绑定的。
