### ISSUE TITLE
state 感觉不是很好用，启动前需要加载所以的依赖？

### ISSUE THREAD

**Issue by Dreampie** [regularjs/regular#34]

**Comment by leeluolee** [comment]
state可以动态加上去，不一定要start之前配置完毕。 关于state的问题  你直接QQ我 或者邮件我吧。  如果你是说按需加载的问题，我敢肯定 应该90%  都是技术误区

**Comment by leeluolee** [comment]
我知道了， 你应该没有打包， requirejs上线是需要打包的, 否则所有模块都是异步加载。

http://regularjs.github.io/regular-state/requirejs/index-min.html
http://regularjs.github.io/regular-state/requirejs/index.html#!/

你可以对比以下两个连接的区别，注意清除缓存

**Comment by Dreampie** [comment]
嗯，谢谢，暂时没有时间弄这个，后面用到了再来反馈

**Comment by Dreampie** [comment]
嗯，谢谢，暂时没有时间弄这个，后面用到了再来反馈
