### ISSUE TITLE
regularjs可以使用其它的模版引擎吗？

### ISSUE THREAD

**Issue by git-lt** [regularjs/regular#37]
默认的模版引擎与后台模板引擎冲突

**Comment by leeluolee** [comment]
如果你指的是语法的话.  可以使用 

```js
Regular.config({'BEGIN':'{{', END: '}}'})
```

在模板里

```
<div> {{blog.title}} </div>
```

http://regularjs.github.io/reference/?api-zh#api-reference-静态接口-regularconfig

**Comment by git-lt** [comment]
我指的是#if，这个种写法，#if与后台模板冲突

**Comment by leeluolee** [comment]
额  这个肯定没法控制，   #if的 模板是哪款？   像ftl这种  只是会有包裹符号吧  比如  `<#if >`

**Comment by leeluolee** [comment]
我知道你所指的模板了， 我也用到了...  velocity吧  ，我真心觉得这个模板有点反人类， 可惜nodejs和java都支持的服务端模板并不多。

你在velocity中有两种方式  避免冲突。  

1. 全局不解析

```
#[[
    这段内容将不被 Velocity 引擎解析，原文打出。

    * #define()
    * ${blah

]]#
```

2. 只转义#

```
{\#if name = hello }  <h2> hello</h2> {/if}
```

**Comment by git-lt** [comment]
@leeluolee 后台模板确实是velocity， 非常感谢你的解答，在后期的项目里争取用上！3Q
