### ISSUE TITLE
RegularJS 支持深度 $watch 么?

### ISSUE THREAD

**Issue by infinnie** [regularjs/regular#48]
类似 VueJS 的
```javascript
this.$watch('todos', function (todos) { 
	todoStorage.save(todos); 
}, { deep: true }); 
```
之中的 { deep: true }

**Comment by leeluolee** [comment]
deep  有，  但是只支持一级的检查。但是 组件会emit 一个  '$update'  事件， 当任意 数据发生变化会触发.  脏检查在使用上有时能提供一些数据操作的自由度，  但是也会引入一些限制。

现在其实对于这种需求， 我会使用redux等简单的数据框架，  将action 与 实际数据操作分离出来。  单纯深度监听数据，不是一个好的实践。

**Comment by infinnie** [comment]
其实可以考虑把深度 $watch couple 在脏检查的时刻

以上纯乱猜，如有原理上无法实现或者对性能具有严重影响请原谅

**Comment by leeluolee** [comment]
目前这个方案，不太适合直接 做进 LifeCycle 中。
