### ISSUE TITLE
嵌套组件调用外层组件的方法this没有指向外层组件

### ISSUE THREAD

**Issue by zjzhome** [regularjs/regular#51]
波神, 最近写了一个简单的ajax组件,调用方式类似这样
```html
<ajax url="data.json" dataType="json" onSuccess={this.handleData}></ajax>
```
直接将请求成功或者失败的方法作为属性, 但这样调用的外层组件的方法内的this不是指向外层组件的. 

把它放到模板内:
```javascript
	var Demo = Regular.extend({
		template: '<div class="content">{user}<ajax url="data.json" dataType="json" onSuccess={this.handleData}></ajax></div>',
		data: {
			user: ''
		},
		handleData: function(result) {
			var html = 'name: ' + result.name + ', gender: ' + result.gender;
			this.data.user = html;  //这里的this指向了window, 报错
			this.$update();  
		}
	});

	var demo = new Demo();

	demo.$inject('#app')
```

**Comment by leeluolee** [comment]
{this.xx.bind(this)}  但是这种应该在ajax组件内部emit事件  < ajax  on-success={this.handle($event)}  />比较好    组件内部  this.$emit("success", 事件参数)

**Comment by zjzhome** [comment]
谢波神，果然应该在组件中触发事件。{this.xx.bind(this)}这样的话会报错误：Uncaught Error: there may a circular dependencies reaches

**Comment by leeluolee** [comment]
@zjzhome 嗯。  {this.xx.bind(this)} 其实每次返回的都是新函数， 会导致稳定不下来， 我给了错误的解答。 问题我先关了
