### ISSUE TITLE
label标签上添加on-click会触发两次

### ISSUE THREAD

**Issue by yinhaoqi** [regularjs/regular#52]
<label on-click={this.select($event)}><input type="checkbox" name="ck" value="1"></label>
会出现触发两次点击事件

**Comment by leeluolee** [comment]
http://stackoverflow.com/questions/8238599/jquery-click-fires-twice-when-clicking-on-label 这个问题 参考下这个爆栈网的回答。 应该不算bug, 是浏览器表现
