### ISSUE TITLE
forEach, filter, map等ES5的兼容处理函数在IE8和现代浏览器中使用不完全一致

### ISSUE THREAD

**Issue by rainfore** [regularjs/regular#59]
遍历时数组可能会有变动，所以不能用简单的for循环。

建议直接复制mozilla的兼容代码
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Polyfill

**Comment by leeluolee** [comment]
内部 考虑 直接处理成  _.forEach  吧，  就是怕会影响到之前版本的

**Comment by rainfore** [comment]
不会的，你写的那个forEach可以用的话，官方的那个也可以用。官方的就是处理了一些异常情况

**Comment by leeluolee** [comment]
因为不想引入额外的代码了，  Regularjs的职责应该不是提供这些polyfill

**Comment by leeluolee** [comment]
fix at 8a5ab189aa3df722712ce34663e361d0b72490dd
