### ISSUE TITLE
IE8 Compatibility Problems

### ISSUE THREAD

**Issue by rainfore** [regularjs/regular#60]
1. 删除元素中不存在的属性会报错
```
function animationDestroy(element){
    return function(){
        delete element.onenter;
        delete element.onleave;
    }
}
```

2. `<iframe>`标签中包含text时报错

**Comment by leeluolee** [comment]
iframe 包含text 报错 ， 可能暂时不做处理了， 我新建一个bug 单独处理  。  这个要求 创建textNode的时候对上层环境可知，  这个和 之前一个issue 要求 option 对外层select是可知的  问题是一样的，  后续一起作为一个整体的 issue 处理
