### ISSUE TITLE
list对象的时候更加简明

### ISSUE THREAD

**Issue by xmory** [regularjs/regular#62]
允许 list 指令 可以对 对象使用

**Comment by leeluolee** [comment]
版本 0.5.0 增加

**Comment by leeluolee** [comment]
简要说明， 假如有以下模板
```js
{#list json as item}<div>{item_index}:{item}:{item_key}</div> {/list}
```
如果list,的目标是 一个对象, 比如 `data.json = {a: 5, b:4, c:3}`
- 全局除了`item`, `item_index` ， 还增加了 __`item_key`__ 代表当前key值， 下标仍然存在，代表项的数字下标

所以上面的例子， 输出的结构的就是

```js
<div>0:5:a</div>
<div>1:4:b</div>
<div>2:3:c</div>
```

注意， 数组的diff判断依据是数组的每个项目， 但是对象的diff的判断依据是value.
