### ISSUE TITLE
请问如何在模板里格式化时间？

### ISSUE THREAD

**Issue by heshunwq** [regularjs/regular#65]
写temple的时候，如何格式化时间？
![regalr](https://cloud.githubusercontent.com/assets/5101286/11528119/bea206a8-991f-11e5-8fd7-479fc9ee6b38.png)

**Comment by leeluolee** [comment]
http://regularjs.github.io/guide/zh/basic/filter.html#-format  参考下这个例子  写一个过滤器，  你的要求 直接使用例子中的format 即可

**Comment by leeluolee** [comment]
如果没问题， 我稍后就关了
