### ISSUE TITLE
isolate问题

### ISSUE THREAD

**Issue by DophinL** [regularjs/regular#68]
```html
<xselect isolate>content</xselect>
```

如果标签上加了isolate，且有内嵌内容，会报错
![image](https://cloud.githubusercontent.com/assets/8707316/11607502/fe136a32-9b83-11e5-8fff-07db715f481d.png)

**Comment by leeluolee** [comment]
__这个bug有点大的。。。__

https://github.com/regularjs/regular/blob/4408e0caf37493fce94a726a1237d8e64fdc1a81/test/spec/browser-bugfix.js#L559   随0.4.3 一起发布

**Comment by DophinL** [comment]
好嘞
