### ISSUE TITLE
在初始化的时候，regular不应该让强制把父组件的值传给子组件

### ISSUE THREAD

**Issue by rainfore** [regularjs/regular#78]
如下：
```xml
<calendar date={outerDate} />
```

刚开始outerDate为undefined的时候，应该从calendar中把有值的date传向外面。

**Comment by lifeforfun** [comment]
子组件不应该影响父组件的值吧，这样容易导致数据混乱，一个组件应该从外部接收固定属性名的数据通过$emit触发将处理后的数据回传给外部调用者，这样才能保证数据流单向性

**Comment by rainfore** [comment]
regular是双向绑定，和react不一样，不一定都要用$emit方式，数据流可以从外向内也可以从内向外。

参见：http://regular-ui.github.io/jsmodule/calendar.html

**Comment by leeluolee** [comment]
@lifeforfun  设计的 默认就是父子形成双向绑定。 很多时候双向绑定并不是完全的 不佳实践。 在你能控制的情况下，在局部环境下使用双向绑定 可以简化你的业务逻辑。 

当然 你可以通过 isolate 等 控制你的数据流向， 以实现单向数据流。 比如我们这边结合redux也是使用的单向数据流

**Comment by leeluolee** [comment]
逻辑梳理下， 当组件b编译遇到  <A  a = {b} > 时  相当于

```js
new A({
   data: {
       a: b.data.b
   }
})
```

如果经过这段初始化，  a.data.a !== b.data.b  那只有可能是a的初始化过程中主动修改了b的值(有可能是在config中整理了数据)。 所以此时将a的值同步为b应该是没有问题的

**Comment by mejustme** [comment]
这个好，常常遇到这个问题，初始化的时候，子组件config修正了数据，父watch() -> 子watch(), 父watch又把数据覆盖了之前config中的修正值了。
