### ISSUE TITLE
regular模板中可以加上遍历object属性和值的语法

### ISSUE THREAD

**Issue by sparkmorry** [regularjs/regular#80]
遇到需要解析一个object（map）的任务，尝试用{#list}{/list}可以解析出object的值，但是想把key值也显示出来，用item_index不行。。希望能有list内部可以读取{item} 和{item_key}这样的

**Comment by leeluolee** [comment]
直接使用  item_key .已经支持了的

**Comment by rainfore** [comment]
以后稳定了可以在文档里更新一下。还有{#list 2...5}这个在文档里也没有，上次有人问我。

**Comment by sparkmorry** [comment]
嗯 瞄了一眼文档木有看到。。
