### ISSUE TITLE
服务端渲染支持

### ISSUE THREAD

**Issue by leeluolee** [regularjs/regular#83]
目前其实已经完成。  还在做的是服务端渲染配套的单页系统框架的整理，并且早已有了一个在运行的线上项目， 在考虑先内部完善后再发布，或是推广出去，集思广益，。

这个issue会包含
- [x] 一个`Server.render(Component, definition)` (已完成)
- [x] 一个配套的`regular-state`的框架，用于整合Regular与第三方路由库stateman(可用于服务端) (已完成)
- [x] 一个完整的单页范例  (已完成)
- [ ]   文档未完成
- [x]   单元测试未完成，这个工作量不大， 因为Regular和Stateman都是经过了充分的测试， Regular-state仅仅是功能整合

regular-state其实是14年就完成的一个东西， 不过一直是内部在使用, 在没有文档的情况下已经对内支持了几个项目了，有几个复杂度还挺高，所以应该设计的还算清晰简单。 这个v0.5的发布会同时将其对外公布它. 仓库在这里  https://github.com/regularjs/regular-state

**Comment by measca** [comment]
我很喜欢RegularJS. 我在学习 SPA-example 的时候发现 它引用了 regular-state/server ,但我在 regular-state 里面没发现 server.js 这个文件,是被删除了吗?

**Comment by leeluolee** [comment]
@measca  应该是分支不同  在next分支里
