### ISSUE TITLE
需要一个r-options指令

### ISSUE THREAD

**Issue by leeluolee** [regularjs/regular#86]
目前后续select节点内部的option列表的变化，Regular无法感知到。虽然一直建议去创建一个组件来解决这个问题，  可能内部直接提供一个`r-options`也是有需要的

``` js

<select r-options={options}  value=xx>  </select>

```

代替

``` js
<select >
{#list options as option}
   <option value={option.value}> {option.name} <option>
{/list}
</select>

```

**Comment by rainfore** [comment]
这个问题我也遇到过，建议用组件来实现吧，Regular处理基本逻辑就可以了。

**Comment by leeluolee** [comment]
轻量实现， 仅仅只是满足， list options的不足，  复杂需求 还是建议组件。 现在写个DEMO 就要引入组件有些麻烦

**Comment by leeluolee** [comment]
暂时不处理，可以交由组件实现
