### ISSUE TITLE
组件ref引用丢失

### ISSUE THREAD

**Issue by dkypooh** [regularjs/regular#88]

**Comment by dkypooh** [comment]
嵌套组件  <parent><child ref="child"></child></parent> 父组件destory了， 然后再次 new的这个父组件， 子组件的ref没有拿到

**Comment by leeluolee** [comment]
由于组件引入了全局状态，比如注册了全局body的事件，但是全局不在组件的回收范围内，应该在组件destroy中处理。  

会考虑在文档中强调这个问题  @dkypooh
