### ISSUE TITLE
optimization for arguments

### ISSUE THREAD

**Issue by fengzilong** [regularjs/regular#94]
Using slice on arguments prevents optimizations in some JavaScript engines
for more details, please read:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments#Description
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments

**Comment by fengzilong** [comment]
vue已有针对arguments的优化

**Comment by leeluolee** [comment]
Good

**Comment by leeluolee** [comment]
PR has been merged

**Comment by fengzilong** [comment]
Glad i could help, have a nice day:sunny:
